client_id = "aea691dcc1d2d5cd01ac18c7263b4534"
name = "Stow Quote Development"
application_url = "https://PLACEHOLDER.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "reinforced-beds-ait-staging.myshopify.com"

[access_scopes]
scopes = "write_draft_orders,read_draft_orders,read_customers,write_customers"

[auth]
redirect_urls = [ "https://PLACEHOLDER.ngrok-free.app/auth/callback" ]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled", "orders/paid" ]
uri = "/webhooks"
