client_id = "PLACEHOLDER_DEVELOPMENT_CLIENT_ID"
name = "Stow & Settle Quotations (Development)"
application_url = "https://PLACEHOLDER.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "PLACEHOLDER.myshopify.com"

[access_scopes]
scopes = "write_draft_orders,read_draft_orders,read_customers,write_customers"

[auth]
redirect_urls = [ "https://PLACEHOLDER.ngrok-free.app/auth/callback" ]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled", "orders/paid" ]
uri = "/webhooks"
