import { useMemo, useState } from "react";
import { formatGBP, parsePoundsToPence } from "../pricing.js";
type Option={description:string;price:string};
type Initial={customerName?:string;customerEmail?:string;customerTelephone?:string;customerAddress?:string;deliveryPostcode?:string;enquiryDate?:string;enquiryReference?:string;internalNotes?:string;seatingStyleId?:string;description?:string;seatingFullPrice?:string;deliveryCost?:string;options?:Option[]};
export function QuoteForm({styles,initial={}}:{styles:Array<{id:string;name:string;reference:string}>;initial?:Initial}){
 const [options,setOptions]=useState<Option[]>(initial.options||[]); const [seat,setSeat]=useState(initial.seatingFullPrice||"0.00"); const [delivery,setDelivery]=useState(initial.deliveryCost||"0.00");
 const total=useMemo(()=>{try{return parsePoundsToPence(seat)+parsePoundsToPence(delivery)+options.reduce((s,o)=>s+parsePoundsToPence(o.price),0)}catch{return 0}},[seat,delivery,options]);
 const change=(i:number,key:keyof Option,value:string)=>setOptions(options.map((o,n)=>n===i?{...o,[key]:value}:o));
 return <><div className="card"><h2>Customer</h2><div className="grid"><div className="field"><label>Full name</label><input name="customerName" defaultValue={initial.customerName} required/></div><div className="field"><label>Email address</label><input name="customerEmail" type="email" defaultValue={initial.customerEmail} required/></div><div className="field"><label>Telephone number</label><input name="customerTelephone" defaultValue={initial.customerTelephone}/></div><div className="field"><label>Delivery postcode</label><input name="deliveryPostcode" defaultValue={initial.deliveryPostcode}/></div><div className="field"><label>Enquiry date</label><input name="enquiryDate" type="date" defaultValue={initial.enquiryDate} required/></div><div className="field"><label>Original enquiry/reference</label><input name="enquiryReference" defaultValue={initial.enquiryReference}/></div></div><div className="field"><label>Billing or delivery address</label><textarea name="customerAddress" defaultValue={initial.customerAddress}/></div><div className="field"><label>Internal notes (never shown to customer)</label><textarea name="internalNotes" defaultValue={initial.internalNotes}/></div></div>
 <div className="card"><h2>Seating</h2><div className="field"><label>Seating style</label><select name="seatingStyleId" defaultValue={initial.seatingStyleId}><option value="">Select a style</option>{styles.map(s=><option value={s.id} key={s.id}>{s.name} ({s.reference})</option>)}</select></div><div className="field"><label>Description and specification</label><textarea name="description" rows={5} defaultValue={initial.description}/></div></div>
 <div className="card"><h2>Pricing</h2><p className="muted">All amounts are GBP and inclusive of VAT.</p><div className="field"><label>Seating full price</label><input name="seatingFullPrice" inputMode="decimal" value={seat} onChange={e=>setSeat(e.target.value)} required/></div><h3>Additional options</h3>{options.map((o,i)=><div className="option-row" key={i}><input aria-label={`Option ${i+1} description`} name="optionDescription" placeholder="Description" value={o.description} onChange={e=>change(i,"description",e.target.value)} required/><input aria-label={`Option ${i+1} price`} name="optionPrice" inputMode="decimal" placeholder="0.00" value={o.price} onChange={e=>change(i,"price",e.target.value)} required/><button type="button" className="danger" onClick={()=>setOptions(options.filter((_,n)=>n!==i))}>Remove</button></div>)}<button type="button" className="secondary" onClick={()=>setOptions([...options,{description:"",price:"0.00"}])}>Add option</button><div className="field"><label>Delivery cost</label><input name="deliveryCost" inputMode="decimal" value={delivery} onChange={e=>setDelivery(e.target.value)} required/></div><input type="hidden" name="optionCount" value={options.length}/><div className="total"><span>Grand total</span><span>{formatGBP(total)}</span></div></div><button type="submit">Save draft revision</button></>;
}
