import { db } from "./db.server.ts";
import { buildDraftOrderInput } from "./shopify-draft-order.js";
import { generateQuotePdf } from "./pdf.server.js";
import { storePrivateArtifact } from "./storage.server.js";

export async function claimJob(){const jobs=await db.$queryRaw`UPDATE "Job" SET status='RUNNING', "lockedAt"=NOW(), attempts=attempts+1 WHERE id=(SELECT id FROM "Job" WHERE status='PENDING' AND "availableAt"<=NOW() ORDER BY "createdAt" FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *`;return jobs[0]||null}
async function shopifyGraphql(shop,query,variables){const session=await db.session.findFirst({where:{shop,isOnline:false},orderBy:{expires:"desc"}});if(!session)throw new Error("No offline Shopify session is available for this shop.");const response=await fetch(`https://${shop}/admin/api/2026-07/graphql.json`,{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Access-Token":session.accessToken},body:JSON.stringify({query,variables})});if(!response.ok)throw new Error(`Shopify request failed (${response.status}).`);const result=await response.json();if(result.errors?.length)throw new Error(result.errors.map(e=>e.message).join("; "));return result.data}
const CREATE=`mutation CreateDraft($input: DraftOrderInput!) { draftOrderCreate(input:$input) { draftOrder { id invoiceUrl } userErrors { field message } } }`;
const UPDATE=`mutation UpdateDraft($id: ID!, $input: DraftOrderInput!) { draftOrderUpdate(id:$id,input:$input) { draftOrder { id invoiceUrl } userErrors { field message } } }`;
export async function processJob(job){const quote=await db.quote.findUniqueOrThrow({where:{id:job.quoteId},include:{revisions:{where:{revisionNumber:job.payload.revisionNumber}}}});const revision=quote.revisions[0];if(!revision)throw new Error("Revision not found");if(job.type==="GENERATE_PDF"){const pdf=await generateQuotePdf({quote,revision,paymentUrl:quote.shopifyInvoiceUrl});const key=`quotes/${quote.id}/revision-${revision.revisionNumber}.pdf`;await storePrivateArtifact(key,pdf,"application/pdf");await db.quote.update({where:{id:quote.id},data:{pdfObjectKey:key}})}else if(job.type==="SYNC_SHOPIFY"){const input=buildDraftOrderInput({quote,revision});const data=quote.shopifyDraftOrderId?await shopifyGraphql(quote.shop,UPDATE,{id:quote.shopifyDraftOrderId,input}):await shopifyGraphql(quote.shop,CREATE,{input});const result=data.draftOrderUpdate||data.draftOrderCreate;if(result.userErrors?.length)throw new Error(result.userErrors.map(e=>e.message).join("; "));await db.quote.update({where:{id:quote.id},data:{shopifyDraftOrderId:result.draftOrder.id,shopifyInvoiceUrl:result.draftOrder.invoiceUrl}});await db.job.upsert({where:{idempotencyKey:`pdf:${quote.id}:${revision.revisionNumber}`},update:{},create:{quoteId:quote.id,type:"GENERATE_PDF",idempotencyKey:`pdf:${quote.id}:${revision.revisionNumber}`,payload:{revisionNumber:revision.revisionNumber}}})}else throw new Error(`Unsupported job type ${job.type}`)}
