import type {ActionFunctionArgs,LoaderFunctionArgs} from "react-router";
import {Form,redirect,useActionData,useLoaderData} from "react-router";
import {authenticate} from "../shopify.server";
import {db} from "../db.server";
import {parsePoundsToPence} from "../pricing.js";
import {reviseQuote} from "../quotes.server";
import {QuoteForm} from "../components/QuoteForm";
const pounds=(p:number)=>(p/100).toFixed(2);
export async function loader({request,params}:LoaderFunctionArgs){const {session}=await authenticate.admin(request);const [quote,styles]=await Promise.all([db.quote.findFirstOrThrow({where:{id:params.quoteId,shop:session.shop},include:{revisions:{orderBy:{revisionNumber:"desc"},take:1}}}),db.seatingStyle.findMany({where:{active:true},orderBy:{name:"asc"}})]);return {quote,styles}}
export async function action({request,params}:ActionFunctionArgs){const {session}=await authenticate.admin(request);try{const quote=await db.quote.findFirstOrThrow({where:{id:params.quoteId,shop:session.shop}});const f=await request.formData();const descriptions=f.getAll("optionDescription").map(String),prices=f.getAll("optionPrice").map(String);await db.quote.update({where:{id:quote.id},data:{customerName:String(f.get("customerName")),customerEmail:String(f.get("customerEmail")),customerTelephone:String(f.get("customerTelephone")||"")||null,customerAddress:String(f.get("customerAddress")||"")||null,deliveryPostcode:String(f.get("deliveryPostcode")||"")||null,enquiryDate:new Date(String(f.get("enquiryDate"))),enquiryReference:String(f.get("enquiryReference")||"")||null,internalNotes:String(f.get("internalNotes")||"")||null,seatingStyleId:String(f.get("seatingStyleId")||"")||null}});await reviseQuote(quote.id,{specification:{description:String(f.get("description")||"")},seatingFullPricePence:parsePoundsToPence(f.get("seatingFullPrice")),deliveryCostPence:parsePoundsToPence(f.get("deliveryCost")),additionalOptions:descriptions.map((description,i)=>({description,pricePence:parsePoundsToPence(prices[i])}))},session.id);return redirect(`/app/quotes/${quote.id}`)}catch(e){return {error:e instanceof Error?e.message:"Unable to save revision"}}}
export default function Edit(){const {quote,styles}=useLoaderData<typeof loader>();const result=useActionData<typeof action>();const r=quote.revisions[0];const p=r.pricing as any;const spec=r.specification as any;return <><h1>Edit {quote.reference}</h1><p className="muted">Saving creates a new revision; revision {r.revisionNumber} remains unchanged.</p>{result?.error&&<div className="card">{result.error}</div>}<Form method="post"><QuoteForm styles={styles} initial={{customerName:quote.customerName,customerEmail:quote.customerEmail,customerTelephone:quote.customerTelephone||"",customerAddress:quote.customerAddress||"",deliveryPostcode:quote.deliveryPostcode||"",enquiryDate:new Date(quote.enquiryDate).toISOString().slice(0,10),enquiryReference:quote.enquiryReference||"",internalNotes:quote.internalNotes||"",seatingStyleId:quote.seatingStyleId||"",description:String(spec.description||""),seatingFullPrice:pounds(r.seatingFullPricePence),deliveryCost:pounds(r.deliveryCostPence),options:p.additionalOptions.map((o:any)=>({description:o.description,price:pounds(o.pricePence)}))}}/></Form></>}
